### ISSUE TITLE
Ubuntu 16.04 LTS support 

### ISSUE THREAD

**Issue by JohannesTK** [xplico/xplico#14]
Great work on the project!

I might be mistaken but looking from your latest commit you are getting ready for Ubuntu 16.04 LTS: https://github.com/xplico/xplico/commit/f034b196562bf6c6f01a51ab486435b64b761c61. 

That's why I'd like to ask if you also have an approx timeline/date for it?

Cheers!

**Comment by gnlcosta** [comment]
Yes, we are migrating to PHP7 (with retro compatibility with PHP5) to be able to install Xplico also in all distributions that use or which will use PHP7.
I hope to complete the porting (except for Proxy functionality)  and the tests in the next weeks.
If you would like to test Xplico on Ubuntu 16.04: http://projects.xplico.org/test/xplico_1.2.0_amd64.deb

Proxy functionality will be integrated in a next step because it requires a deep knowledge of CakePHP to modify it, and also because I do not know how many actually use or have used this feature (not trivial for the era in which it was made).

Ciao from Venezia
