### ISSUE TITLE
Call of session_mng.pyc gives an error

### ISSUE THREAD

**Issue by M0Rf30** [xplico/xplico#16]
```
/opt/xplico/script/session_mng.pyc: riga 1: $'\026\r\r': comando non trovato
/opt/xplico/script/session_mng.pyc: riga 2:
$'۶oX\2627\343\021@sy\fdd\001lZdd\001l\001Z\001dd\001l\002Z\002dd\001l\003Z\003dd\001l\004Z\004dd\001l\005Z\005dd\001l\006Z$
/opt/xplico/script/session_mng.pyc: riga 3: Z: comando non trovato
/opt/xplico/script/session_mng.pyc: riga 4: $'\001d\003Z\vd\004Z\fd\005d\006\204Z\rd\ad\b\204Z\016d': comando non trovato
/opt/xplico/script/session_mng.pyc: riga 5: errore di sintassi vicino al token non atteso ")"
/opt/xplico/script/session_mng.pyc: riga 5: `�Z^Oe^Pd^Kk^Bru^Ly)e^Cj^Ce^Aj^Qd^Ld^A�^B^Yd^M�^B\^BZ^RZ^SWn/^De^Cj^Tk'

```

**Comment by M0Rf30** [comment]
Probably you don't correctly sanitize the call and special characters are passed to session_mng

**Comment by gnlcosta** [comment]
Hi,
this issue is related that pyc is a pseudo-binary file and to run it Linux must invoke the right application, this application is described by the firsts bytes of the file (like #!/bin/bash for the bash scripts). On Ubuntu you have to install binfmt-support .
Some info are here: http://forum.xplico.org/viewtopic.php?f=3&t=488&p=1204&hilit=binfmt+support#p1204

Ciao e grazie per i contributi.

**Comment by M0Rf30** [comment]
in order to avoid binfmt installation and binfmt service execution why not to install also py files and their pyc?

**Comment by gnlcosta** [comment]
Right.
In the past py script wasn't open source. Therefore (now) pyc is only for historical reasons.
In the next release I will remove pyc in favor of py.

**Comment by M0Rf30** [comment]
I've done a PR leaving pyc bytecode installation, that should optimize py modules execution
